### ISSUE TITLE
Build issues in OSX

### ISSUE THREAD

**Issue by igorsyl** [braxtonmckee/nativepython#35]
I had to make the following changes to build in OSX:

1. Add explicit cast for (Type*) in AlternativeType.hpp:49 to fix Apple LLVM error below.

```
In file included from typed_python/all.cpp:10:
In file included from typed_python/_types.cpp:9:
In file included from typed_python/AllTypes.hpp:19:
typed_python/AlternativeType.hpp:49:19: error: cannot initialize a variable of type 'Type *' with an lvalue of type 'Function *'
            Type* t = method_pair.second;
                  ^   ~~~~~~~~~~~~~~~~~~

```
2. Use MACOSX_DEPLOYMENT_TARGET=10.14 make
Source: https://stackoverflow.com/questions/33738885/python-setuptools-not-including-c-standard-library-headers

If you agree I can add a pull request for both of these.

**Comment by braxtonmckee** [comment]
Yeah that sounds good. Let's also add a config to travis so we don't
regress.
